import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { collection, addDoc, serverTimestamp, getDoc, doc } from 'firebase/firestore';
import { db, storage } from '../lib/firebase';
import { 
  Camera, 
  MapPin, 
  Mic, 
  Send, 
  Leaf, 
  ChevronLeft,
  X,
  AlertCircle
} from 'lucide-react';

const ACTIVITY_TYPES = [
  { id: 'snare_removal', label: 'Snare Removal', unit: 'snares' },
  { id: 'wildlife_sighting', label: 'Wildlife Sighting', unit: 'animals' },
  { id: 'nest_check', label: 'Nest Check', unit: 'nests' },
  { id: 'patrol_log', label: 'Patrol Log', unit: 'kilometers' },
  { id: 'illegal_activity_report', label: 'Illegal Activity', unit: 'incidents' },
];

export default function LogActivity() {
  const navigate = useNavigate();
  const { currentUser } = useAuth();
  const fileInputRef = useRef(null);
  
  const [formData, setFormData] = useState({
    activityType: '',
    quantityValue: '',
    description: '',
  });
  
  const [photoFile, setPhotoFile] = useState(null);
  const [photoPreview, setPhotoPreview] = useState(null);
  const [locationStatus, setLocationStatus] = useState('pending'); // pending, scanning, acquired, error
  const [gpsData, setGpsData] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Handle Photo Capture/Upload
  const handlePhotoUpload = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setPhotoFile(file);
      const previewUrl = URL.createObjectURL(file);
      setPhotoPreview(previewUrl);
      
      setLocationStatus('scanning');
      setGpsData(null);
      
      // Capture Real-Time GPS Coordinates
      if ('geolocation' in navigator) {
        navigator.geolocation.getCurrentPosition(
          (position) => {
            setGpsData({
              lat: position.coords.latitude,
              lng: position.coords.longitude,
              accuracy: position.coords.accuracy
            });
            setLocationStatus('acquired');
          },
          (error) => {
            console.error("GPS Capture Error:", error);
            setLocationStatus('error');
          },
          { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }
        );
      } else {
        setLocationStatus('error');
      }
    }
  };

  const removePhoto = () => {
    setPhotoFile(null);
    setPhotoPreview(null);
    setLocationStatus('pending');
    setGpsData(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const selectedTypeObj = ACTIVITY_TYPES.find(t => t.id === formData.activityType);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!photoFile || !currentUser) return;
    setIsSubmitting(true);
    
    try {
      // 1. Fetch exact user context for accurate metadata
      const userDocSnap = await getDoc(doc(db, 'users', currentUser.uid));
      const orgId = userDocSnap.exists() ? 
        (userDocSnap.data().organizationId || userDocSnap.data().studentProfile?.university || 'global') 
        : 'global';

      // 2. Upload Photo to Firebase Cloud Storage
      const fileExt = photoFile.name.split('.').pop() || 'jpg';
      const fileName = `evidence/${currentUser.uid}/${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
      const storageRef = ref(storage, fileName);
      
      await uploadBytes(storageRef, photoFile);
      const downloadUrl = await getDownloadURL(storageRef);

      // 3. Save immutable evidence metadata record to Firestore
      await addDoc(collection(db, 'submissions'), {
        userId: currentUser.uid,
        organizationId: orgId, // Dynamically sourced from user profile
        activityType: formData.activityType,
        quantityValue: Number(formData.quantityValue),
        quantityUnit: selectedTypeObj?.unit || '',
        description: formData.description,
        photoStoragePath: downloadUrl,
        photoHash: 'pending-sha256-hash', // To be generated by Cloud Function ML
        gpsCoordinates: gpsData ? { lat: gpsData.lat, lng: gpsData.lng } : null,
        gpsAccuracy: gpsData ? gpsData.accuracy : null,
        submittedAt: serverTimestamp(),
        exifTimestamp: serverTimestamp(),
        deviceId: 'web-pwa',
        appVersion: '1.0.0',
        offlineSubmission: false,
        verificationStatus: 'pending',
        verificationScore: 0,
        creditsAwarded: 0
      });

      setIsSubmitting(false);
      navigate('/', { replace: true });
    } catch (error) {
      console.error("Submission failed:", error);
      alert("Failed to upload evidence. Please check your connection.");
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <div className="bg-white border-b border-gray-100 px-4 py-4 flex items-center sticky top-0 z-50">
        <button 
          onClick={() => navigate(-1)} 
          className="p-2 -ml-2 text-gray-500 hover:text-gray-900 transition-colors"
        >
          <ChevronLeft size={24} />
        </button>
        <h1 className="text-xl font-bold text-gray-900 ml-2">Log Activity</h1>
      </div>

      <div className="flex-1 px-5 py-6">
        <form onSubmit={handleSubmit} className="space-y-6">
          
          {/* Photo Upload Section */}
          <div>
            <label className="block text-sm font-bold text-gray-900 mb-2">Evidence Photo *</label>
            {!photoPreview ? (
              <div 
                onClick={() => fileInputRef.current?.click()}
                className="w-full h-48 border-2 border-dashed border-forest-300 bg-forest-50/50 rounded-3xl flex flex-col items-center justify-center cursor-pointer hover:bg-forest-50 transition-colors"
              >
                <div className="w-14 h-14 bg-white rounded-full flex items-center justify-center shadow-sm text-forest-500 mb-3">
                  <Camera size={28} />
                </div>
                <p className="text-forest-800 font-semibold text-sm">Tap to take photo</p>
                <p className="text-forest-600/70 text-xs mt-1">Must include GPS EXIF data</p>
              </div>
            ) : (
              <div className="relative w-full h-64 rounded-3xl overflow-hidden shadow-sm group">
                <img src={photoPreview} alt="Evidence preview" className="w-full h-full object-cover" />
                <button 
                  type="button"
                  onClick={removePhoto}
                  className="absolute top-3 right-3 w-8 h-8 bg-black/50 backdrop-blur-md rounded-full flex items-center justify-center text-white hover:bg-red-500 transition-colors"
                >
                  <X size={16} />
                </button>
                
                {/* Real-time GPS Overlay */}
                <div className="absolute bottom-3 left-3 right-3 bg-black/60 backdrop-blur-md rounded-xl p-3 flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                    locationStatus === 'acquired' ? 'bg-green-500 text-white' : 
                    locationStatus === 'error' ? 'bg-red-500 text-white' : 'bg-orange-500 text-white animate-pulse'
                  }`}>
                    <MapPin size={16} />
                  </div>
                  <div className="flex-1">
                    <p className="text-white text-xs font-bold">
                      {locationStatus === 'acquired' ? 'GPS Locked' : 
                       locationStatus === 'error' ? 'GPS Failed' : 'Scanning Coordinates...'}
                    </p>
                    <p className="text-white/70 text-[10px]">
                      {locationStatus === 'acquired' && gpsData 
                        ? `Accuracy: ${Math.round(gpsData.accuracy)} meters` 
                        : locationStatus === 'error' ? 'Please enable location services' : 'Awaiting satellite fix'}
                    </p>
                  </div>
                </div>
              </div>
            )}
            <input 
              type="file" 
              accept="image/*" 
              capture="environment" 
              className="hidden" 
              ref={fileInputRef}
              onChange={handlePhotoUpload}
            />
          </div>

          {/* Activity Type Selection */}
          <div>
            <label className="block text-sm font-bold text-gray-900 mb-2">Activity Type *</label>
            <div className="grid grid-cols-2 gap-3">
              {ACTIVITY_TYPES.map((type) => (
                <button
                  key={type.id}
                  type="button"
                  onClick={() => setFormData({ ...formData, activityType: type.id })}
                  className={`p-3 rounded-2xl border text-sm font-semibold flex items-center gap-2 transition-all ${
                    formData.activityType === type.id 
                      ? 'border-forest-500 bg-forest-50 text-forest-700 ring-2 ring-forest-500/20' 
                      : 'border-gray-200 bg-white text-gray-600 hover:border-gray-300'
                  }`}
                >
                  <Leaf size={16} className={formData.activityType === type.id ? 'text-forest-500' : 'text-gray-400'} />
                  {type.label}
                </button>
              ))}
            </div>
          </div>

          {/* Quantity Input (Dynamic based on type) */}
          {formData.activityType && (
            <div className="animate-in fade-in slide-in-from-top-2">
              <label className="block text-sm font-bold text-gray-900 mb-2">Quantity *</label>
              <div className="relative">
                <input
                  type="number"
                  min="1"
                  required
                  value={formData.quantityValue}
                  onChange={(e) => setFormData({ ...formData, quantityValue: e.target.value })}
                  className="w-full pl-5 pr-24 py-4 bg-white border border-gray-200 rounded-2xl focus:ring-2 focus:ring-forest-500/20 focus:border-forest-500 outline-none text-lg font-bold transition-all"
                  placeholder="0"
                />
                <div className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 font-medium bg-gray-100 px-3 py-1 rounded-lg text-sm">
                  {selectedTypeObj?.unit}
                </div>
              </div>
            </div>
          )}

          {/* Voice Note / Description */}
          <div>
            <label className="block text-sm font-bold text-gray-900 mb-2">Field Notes (Optional)</label>
            <div className="relative">
              <textarea
                rows="3"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="w-full p-4 bg-white border border-gray-200 rounded-2xl focus:ring-2 focus:ring-forest-500/20 focus:border-forest-500 outline-none text-sm resize-none transition-all"
                placeholder="Add details about the location or activity..."
              ></textarea>
              
              {/* Voice Note Recording Button (Low Literacy Support) */}
              <button 
                type="button"
                className="absolute bottom-3 right-3 w-10 h-10 bg-forest-100 text-forest-600 rounded-full flex items-center justify-center hover:bg-forest-200 transition-colors"
                title="Record Voice Note"
              >
                <Mic size={20} />
              </button>
            </div>
          </div>

          {/* Trust Engine Warning */}
          <div className="bg-blue-50 border border-blue-100 rounded-2xl p-4 flex gap-3 items-start">
            <AlertCircle size={20} className="text-blue-500 shrink-0 mt-0.5" />
            <p className="text-xs text-blue-800 font-medium leading-relaxed">
              Your submission will be securely hashed and analyzed by the ConservationCred Trust Engine for duplicate detection and GPS verification.
            </p>
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={!photoPreview || !formData.activityType || !formData.quantityValue || locationStatus !== 'acquired' || isSubmitting}
            className="w-full bg-forest-600 text-white font-bold text-lg py-4 rounded-2xl hover:bg-forest-700 active:scale-[0.98] transition-all disabled:opacity-50 disabled:active:scale-100 flex justify-center items-center gap-2"
          >
            {isSubmitting ? (
              <div className="w-6 h-6 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
            ) : (
              <>
                <Send size={20} />
                Submit for Verification
              </>
            )}
          </button>
          
        </form>
      </div>
    </div>
  );
}
